"use client";

// import { Metadata } from "next";
// import { ErrorWrapper } from "./error-wrapper";
import Link from "next/link";
import {usePathname} from "next/navigation";
import "./style.css";

const navLinks = [
  { href: "/login", name: "Login" },
  { href: "/register", name: "Register" },
  { href: "/forgot-password", name: "Forgot Password" }
];

// export const metadata: Metadata = {
//   title: "Next.js Tutorial",
//   description: "Generated by Next.js",
// };

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        {/* <ErrorWrapper> */}
        {navLinks.map((link) => {
          const isActive =
          pathname === link.href ||
          (pathname.startsWith(link.href) && link.href !== "/");
          return (
          <Link
            className={isActive ? "font-bold mr-4" : "text-blue-500 mr-4"}
            href={link.href}
            key={link.name}
>
            {link.name}
          </Link>
          );
        })}
        {children}
        {/* </ErrorWrapper> */}
        {/* <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
          }}
        >
          <p>Footer</p>
        </footer> */}
      </body>
    </html>
  );
}